### ISSUE TITLE
12.1上play用不了

### ISSUE THREAD

**Issue by daiaji** [taoaoooo/microG_playStore_GCSync#4]
直接卡住。

**Comment by taoaoooo** [comment]
我升级12.1好像遇到了，是不是软件图标变成了安卓logo？打开一直卡在play store的logo，
是的话可以先在/data/adb/modules/microG_tao/system/priv-app/Phonesky/下手动安装一遍apk，安装后手动权限都打开，模块我后面会升级

**Comment by daiaji** [comment]
直接apkpure安装个最新的play市场就能用。

**Comment by taoaoooo** [comment]
> 直接apkpure安装个最新的play市场就能用。

确实

**Comment by taoaoooo** [comment]
已解决
